### ISSUE TITLE
Memory leak when opening editor with this project 

### ISSUE THREAD

**Issue by qarmin** [jegor377/godot-gdgifexporter#12]
When opening editor with this command `godot -e -v -q`, then this leak happens:
```
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112.
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112.
WARNING: cleanup: ObjectDB instances leaked at exit (run with --verbose for details).
   At: core/object.cpp:2132.
Leaked instance: GDScript:18087 - Resource path: 
```

**Comment by jegor377** [comment]
I have no idea why this is happenning. I've been told that there are memory leaks by one guy but he's opened PR that fixed it (Propably. Because I don't remember it now). I've been recently rewriting some of the stuff in other branch but stopped it for now. I don't have much time now to work on this because I'm busy with other stuff but I plan to come back to it in the future. If you would like to further investigate this issue by yourself and open a PR then it would be great.

**Comment by jegor377** [comment]
I have no idea why this is happenning. I've cloned it and opened it without any issue. I'm using Godot 3.2.3 stable. I've been told that there were memory leaks by one guy but he'd opened PR that fixed it (Propably. Because I don't remember it now). I've been recently rewriting some of the stuff in other branch but stopped it for now. I don't have much time now to work on this because I'm busy with other stuff but I plan to come back to it in the future but I'd be happy to review and accept any PR's concerning new features/bugs.
