### ISSUE TITLE
Memory leak when using median_cut

### ISSUE THREAD

**Issue by you-win** [jegor377/godot-gdgifexporter#14]
## Issue
When trying to write more than 2 frames with `median_cut` as the quantizator, Godot's memory usage maxes out my system at ~14 gb (would probably keep going up if I had more than 16 gb). This does not happen when using `enhanced_uniform_quantization`.

#13 does not fix this.

## System specs
OS: Windows 10
CPU: Intel i7-9750H
RAM: 16gb
GPU: NVIDIA RTX 2060

Godot version: 3.2.3
godot-gdgifexporter version: 1.1 and master

## Example
Assume `_images` is an `Array` that contains many `Image` objects. The `Image` objects are obtained by calling `get_viewport().get_texture().get_data()`.
```
func _ready() -> void:
	_gif_exporter = GIF_EXPORTER.new(get_viewport().size.x, get_viewport().size.y)

func _render_gif() -> void:
	var file: File = File.new()
	file.open("user://result.gif", File.WRITE)

	for i in _images.size():
		print("Processing image %s of %s" % [i + 1, _images.size()])
		
#		var median_cut: MedianCut = MEDIAN_CUT.new()
#		_gif_exporter.write_frame(_images[i], gif_frame_delay, median_cut)
		
		var euq = load("res://addons/gdgifexporter/quantization/enhanced_uniform_quantization.gd").new()
		_gif_exporter.write_frame(_images[i], gif_frame_delay, euq)

	file.store_buffer(_gif_exporter.export_file_data())
	file.close()
```
Output of the above code using `enhanced_uniform_quantization.gd`.

![result](https://user-images.githubusercontent.com/7788341/109560220-9b63c200-7aa9-11eb-9e34-b273936e9375.gif)

**Comment by jegor377** [comment]
I'm aware of this issue. It exists for some time, but I didn't fix it. I'm having very little time for programming lately and I promised to myself to fix it shortly after May or maybe faster. I don't know exactly why it happens because I didn't write median cut. Median cut works great with very small images though. This issue happens when the size of the image is bigger than for example 100x100 (I'm not entirely sure what value it is). By the way I don't think that this is memory leak kind of issue. It's more likely due to implementation of median cut algorithm taking very big amount of RAM space. It would propably stop around 30GB. The #13  was fixing other stuff.

**Comment by jegor377** [comment]
Commit f1d8074153cbec74401d8021213ab5bd32057de8 fixes this issue. Check it out and tell me if it works for you! :D
